# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibList = [1,2]
def fibEven(max):
    total = 0
    if fibList[-1] < 4000000:
        fibList.append(fibList[-1] + fibList[-2])
        return fibEven(max)
    for i in fibList:
        if i % 2 == 0:
            total += i
    return total

print fibEven(4000000)
